#! /bin/sh

sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-3 -d 1 2 3 4 5

# https://protesilaos.com/codelog/multihead-bspwm-polybar/

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 40

bspc config normal_border_color "#000000"
bpsc config focused_border_color "#5e81ac" 


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
